### ISSUE TITLE
Create Consumers via Open API Spec

### ISSUE THREAD

**Issue by neo-youre-pena** [Kong/openapi2kong#21]
Hello Kong friends...It's been a few months since my company introduce Kong Konnect, and now I'm working on automating some services configuration. 

Currently, we have an OAS and I'd like to use it as a base for the kong declarative configuration, but unfortunately, I don't know to include the consumers in the open API spec file. 

I will appreciate it if you can point me in a direction of documentation or an example that has what I'm looking for.

**Comment by Tieske** [comment]
That cannot be done right now using these tools. We are working on a new version of the tools that will be able to support it albeit not from within an OAS spec.

The new tools can be found here; https://github.com/Kong/go-apiops. This is a library that will have it's functionality integrated in decK (https://github.com/Kong/deck), but untill that is released, it is available from a temporary cli tool `kced` from it's own repo.

So for now in your use-case I would create an OAS spec, and a separate Kong declarative file holding the consumers. Then you can use `kced` to generate a Kong declarative file (a deck file) from the OAS. And then in a follow up step you can merge the generated deck file, with the deck file holding the consumers (using the `kced merge` command), to get the final file that can be synced to Kong using `deck`.

hth

**Comment by neo-youre-pena** [comment]
Hey @Tieske 👋🏼 Thank you for your quick response! I'm glad to hear your suggestion because I was considering a similar approach. 

My idea is to dump the Kong Konnect configuration, generate the Kong deck file from the OAS and then merge the `services` section into it.  

I didn't know about the `kced merge` command, I was writing my own script to do that hahaha. You save so much work. 

Thank you so much for your help. And off-topic, I'm pretty excited to see Go code in the Kong ecosystem. I'd love to read some articles about why Go and not Lua.
