### ISSUE TITLE
Unable to successfully perform "deck sync" with converted OAS definition file

### ISSUE THREAD

**Issue by aldredb** [Kong/openapi2kong#22]
I'm using deck version v1.25.0 to convert a OpenAPI Spec definition file ([learnservice_oas.yaml](https://github.com/Kong/openapi2kong/blob/master/examples/learnservice_oas.yaml)) to Kong file:

```
deck file openapi2kong \
  --spec learnservice_oas.yaml \
  --output-file learnservice_oas-converted.yaml
```

I performed deck sync  and received the following errors:

```
Error: 3 errors occurred:
	while processing event: {Create} plugin request-validator for route 8672b2ee-d302-54fb-9364-025435e1d0aa failed: HTTP status 400 (message: "schema violation (config.parameter_schema: {\n  {\n    schema = \"the JSONschema is missing a top-level 'type' property\"\n  },\n  {\n    schema = \"the JSONschema is missing a top-level 'type' property\"\n  }\n})")
	while processing event: {Create} plugin request-validator for route d60e3425-0968-5c42-9f5c-a46f637f1516 failed: HTTP status 400 (message: "schema violation (config.parameter_schema: {\n  {\n    schema = \"the JSONschema is missing a top-level 'type' property\"\n  }\n})")
	while processing event: {Create} plugin request-validator for route 5a006f23-2702-5318-a120-06d9a8d3cab6 failed: HTTP status 400 (message: "schema violation (config.parameter_schema: {\n  {\n    schema = \"the JSONschema is missing a top-level 'type' property\"\n  }\n})")
```

There are 3 APIs that trigger the issue, but the root cause is the same. Taking example of "/activities/videos" API:

```
    get:
      tags:
      - activities
      summary: Returns the user's video activity
      operationId: getVideoActivities
      parameters:
      - name: userId
        in: query
        required: true
        schema:
          "$ref": "#/components/schemas/parameterValue"
```

deck file openapi2kong converts the schema `#/components/schemas/parameterValue` to the following:

```
plugins:
    - config:
        parameter_schema:
        - explode: false
          in: query
          name: userId
          required: true
          schema: '{"$ref":"#/definitions/parameterValue","definitions":{"parameterValue":{"anyOf":[{"$ref":"#/definitions/symbol"},{"$ref":"#/definitions/sanitized_number"}]},"sanitized_number":{"maximum":1000000000,"minimum":-1000000000,"type":"integer"},"symbol":{"maxLength":4096,"type":"string"}}}'
          style: form
        version: draft4
      id: 2d99210c-a989-5fb8-b1cf-9efb3a7e39fd
      name: request-validator
      tags: []
which triggers the error schema violation (config.parameter_schema: {\n {\n schema = \"the JSONschema is missing a top-level 'type' property\"\n
```

I changed the schema to `'{"type": "object","definitions":{"parameterValue":{"anyOf":[{"$ref":"#/definitions/symbol"},{"$ref":"#/definitions/sanitized_number"}]},"sanitized_number":{"maximum":1000000000,"minimum":-1000000000,"type":"integer"},"symbol":{"maxLength":4096,"type":"string"}}}'` and there is no more schema violation, which confirms that there needs to be `type` property.

There is no rational reason on why userId should accept 3 different types: `symbol`, `sanitized_number` and an array of `symbol`

Understand that the example is a trivial one, so propose to change to the following:

```
    get:
      tags:
      - activities
      summary: Returns the user's video activity
      operationId: getVideoActivities
      parameters:
      - name: userId
        in: query
        required: true
        schema:
          "$ref": "#/components/schemas/symbol"
```

**Comment by Tieske** [comment]
This is reported in the wrong repo. The problem here is that the top-level `type` field is missing from the JSONschemas. These are required to properly know how to deserialize the data that comes in from a query or header parameter (since they technically always are strings)

Unfortunately the example OAS config contains the JSONschemas without it. I'll update the examples.
